version: '3'
services:
  # ------------
  # backend
  # ------------
  try-csrf:
    container_name: try-csrf
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8888:8888'
    stdin_open: true
    tty: true
    restart: always
  # ------------
  # frontend
  # ------------
  # frontend:
  #   container_name: try-csrf-front
  #   image: node:13.8.0
  #   # build: 
  #   #   context: ./front-csrf
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ./front-csrf:/go/src/github.com/toshick/try-csrf/front-csrf
  #   stdin_open: true
  #   tty: true
  #   working_dir: /go/src/github.com/toshick/try-csrf/front-csrf
  #   command: >
  #     npm run serve

